#!/bin/bash

cp ibcontroller-2.12.2.ini ibcontroller.ini
sed -i s/{{IBLOGIN}}/$IB_LOGIN/g ibcontroller.ini
sed -i s/{{IBPASSWORD}}/$IB_PASSWORD/g ibcontroller.ini
rm -rf tws
mkdir tws
pushd tws
jar -xf ../unixmacosx-949.3d.jar
pushd IBJts
java -cp ../../ibcontroller-2.12.2.jar:jts.jar:total.2013.jar -Xmx512M -XX:MaxPermSize=128M ibcontroller.IBGatewayController ../../ibcontroller-2.12.2.ini &
popd
popd
